### PR TITLE
Fix for #180 + another small one

### PR DESCRIPTION
**Pull request by jrudolph**
Hey Eric,

aside from [#180](http://code.google.com/p/specs/issues/detail?id=180), I fixed another thing we found: You couldn't use verifies if the condition returned a Prop, i.e. when you use any ScalaCheck magic like `:|` or `==>` inside the conditions to check, because then the complete condition is lifted to return a Prop itself. I fixed that in the last commit by readding the implicit view `P <% Prop` and require all the conditions to return a P instead of a Boolean. I added examples to the tests which check that verifies compiles for all the arities.

### CODE REVIEW

**Comment by jrudolph** [comment]
I've just seen, that the same solution once was almost implemented in e62f362020bc7a8daed3a50d9c281effc4747fe7. Almost, because several replacements of `Boolean` to `P` were missed. Those changes were afterwards almost reverted in 1fe459e46491b05a78b928c33dbb4dd08ef300eb leading to the somewhat chaotic situation we had now. If you remember what the problems were why you originally reverted that code, you should probably check if I broke something with doing that again.

**Comment by etorreborre** [comment]
I don't recall the reasons for this. My guess is that either there was some implicit conflicts in some situation or I wanted to be able to keep simple functions A => Boolean in the body of "verify". I don't know if that's still possible with your version, I'm going to pull it and check.

**Comment by jrudolph** [comment]
> I wanted to be able to keep simple functions A => Boolean in the body of "verify"

That should be possible. I added specs for this case for all the arities in the first commit.

**Comment by etorreborre** [comment]
Well that looks fine to me, so I merged your code. Thanks again, I hope that you're having fun with ScalaCheck!

**Pull request merged**
