### PR TITLE
Junit errors

### PR DESCRIPTION
**Pull request by jrudolph**
I tried to improve the integration with JUnit here:
- when a failure occurs from a failing 'be_==' matcher, throw a ComparisonFailure
- for JUnit 4 repackage Assertions to use JUnit 4 ones, which inherit from java.lang.AssertionError

The basic target for this change is better integration with JUnit runners. Specifically, I made these changes with view on the IntelliJ JUnit runner, which with this changes is able to
1. show failures as failures not as errors
2. show the diff-GUI if a simple string comparison fails

### CODE REVIEW

**Comment by jrudolph** [comment]
There's still a small issue, I have to fix: some errors are reported with little helpful stack traces from the guts of the JUnit integration instead of from the failing test itself.

**Comment by jrudolph** [comment]
That should fix the problem from before, what do you think?

**Comment by etorreborre** [comment]
Hi Johannes,

Thanks for your pull requests! I've merged them in. In specs2 I have also taken care of using ComparisonFailures by making sure that some matchers like "beEqualTo" can return the pair of expected/actual values.

Eric.

**Comment by jrudolph** [comment]
Thanks Eric, good to know that it will work specs2 as well.

**Pull request merged**
